name: CI

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch addon/$GITHUB_SHA.txt
      - run: touch base/$GITHUB_SHA.txt
      - run: touch craft/$GITHUB_SHA.txt
      - run: touch trait/$GITHUB_SHA.txt
      - run: mkdir target
      - name: Zip Addon
        run: cd addon && zip -r ../target/AP-Addon.zip .
      - name: Zip Base
        run: cd base && zip -r ../target/AP-Base.zip .
      - name: Zip Craft
        run: cd craft && zip -r ../target/AP-Craft.zip .
      - name: Zip Trait
        run: cd trait && zip -r ../target/AP-Trait.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: Airship-Pirates-Crafts
          path: target
